### ISSUE TITLE
希望能支持Colemak-DH

### ISSUE THREAD

**Issue by pingshunhuangalex** [xkjd27/rime_jd27c#1]
刚入双拼的坑 对各种概念还没有很好的理解 实在是没能力自己修改优化编码

不知道兄台能不能帮忙做一下colemak-dh的编码 搜了一下`colemak`和`星空键道` 这个仓库是我能找到最接近的东西了 谢谢

**Comment by TsFreddie** [comment]
布局没有太大的话，直接拿着用似乎也不是不可以。应该是只有一些韵母的物理位置会变。
直接用星空键道也是个不错的方法，词库更新也比我自己这个频繁一些。我只是考虑到键道的飞键（左右两边各一个zh和ch）会因为位置变化导致左右失衡，还不如想办法去掉才做了个我这个。

如果单独设计个Colemak-DH的方案的话，修复冲突给我一点时间可以慢慢修好。但是添加新词就不能同步了，因为不同布局可用的编码空间也不太一样。

我的建议的话，就是直接配置我现在这个或者原版的星空键道先用一下。实在不喜欢或者用起来很难受再研究怎么生成新的布局。
